use_frameworks!

target 'ADGradientView_Example' do
  pod 'ADGradientView', :path => '../'

  target 'ADGradientView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
